// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2jR2NxBxaLLdzvNz0TFT4wi2KQCRojmI',
    appId: '1:672146364215:web:eb197971d60efa16452cb2',
    messagingSenderId: '672146364215',
    projectId: 'siparis-takip-business',
    authDomain: 'siparis-takip-business.firebaseapp.com',
    storageBucket: 'siparis-takip-business.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnmICzbZUr3OFE_4hSqD_r4kZnDbjhmgk',
    appId: '1:672146364215:android:83d18479cc7223db452cb2',
    messagingSenderId: '672146364215',
    projectId: 'siparis-takip-business',
    storageBucket: 'siparis-takip-business.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsHI38P2zbEBmFX6ZjlLLU0qtjWfoMFYk',
    appId: '1:672146364215:ios:17fcf65ff3fb911e452cb2',
    messagingSenderId: '672146364215',
    projectId: 'siparis-takip-business',
    storageBucket: 'siparis-takip-business.firebasestorage.app',
    iosBundleId: 'com.example.siparis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsHI38P2zbEBmFX6ZjlLLU0qtjWfoMFYk',
    appId: '1:672146364215:ios:17fcf65ff3fb911e452cb2',
    messagingSenderId: '672146364215',
    projectId: 'siparis-takip-business',
    storageBucket: 'siparis-takip-business.firebasestorage.app',
    iosBundleId: 'com.example.siparis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2jR2NxBxaLLdzvNz0TFT4wi2KQCRojmI',
    appId: '1:672146364215:web:fe79db829f3ca60d452cb2',
    messagingSenderId: '672146364215',
    projectId: 'siparis-takip-business',
    authDomain: 'siparis-takip-business.firebaseapp.com',
    storageBucket: 'siparis-takip-business.firebasestorage.app',
  );
}
